---
abstract: 'Represent XML as data structure preserving element order'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Struct
requires:
  Moo: 1.0
  XML::LibXML: 2.0
resources:
  bugtracker: https://github.com/nichtich/XML-Struct/issues
  homepage: https://github.com/nichtich/XML-Struct
  repository: https://github.com/nichtich/XML-Struct.git
version: 0.11
